# Connections probabilities and delays FROM "name"

- name:        S
  S:            0.2       # each S neuron project to each S neuron with probability 0.2
  S_delay:      0.5
  T:            0.8       # each S neuron project to each T neuron with probability 0.8
  T_delay:      1.0
